import streamlit as st
from dotenv import load_dotenv
load_dotenv()

from parser import extract_text
from analyzer import analyze_contract, compare_contracts, rewrite_contract
from formatter import format_results, get_risk_label

import base64
from io import BytesIO
from docx import Document

st.set_page_config(page_title="Dracu-Law", page_icon="⚖", layout="wide")

# ---------- LOGO ----------
def get_base64_image(path):
    try:
        with open(path, "rb") as f:
            return base64.b64encode(f.read()).decode()
    except:
        return None

logo = get_base64_image("logo.png")

# ---------- NAVBAR ----------
st.markdown(f"""
<div style="
display:flex;
align-items:center;
gap:15px;
padding:14px 30px;
background:linear-gradient(90deg,#1c1c1e,#111);
border-bottom:3px solid #c0392b;
border-radius:0 0 12px 12px;
">
{f'<img src="data:image/png;base64,{logo}" style="height:65px">' if logo else "⚖"}
<div>
<div style="font-size:28px;font-weight:800;color:white;">Dracu<span style="color:#e74c3c">-Law</span></div>
<div style="color:#aaa;font-size:12px;">AI Legal Intelligence Engine</div>
</div>
</div>
""", unsafe_allow_html=True)

st.markdown("<h1 style='text-align:center;margin-top:25px;'>AI Contract Intelligence Platform</h1>", unsafe_allow_html=True)
st.divider()

# ---------- SIDEBAR ----------
with st.sidebar:
    st.header("⚙ Settings")
    model_choice = st.selectbox(
        "Model",
        ["llama-3.3-70b-versatile","openai/gpt-oss-120b","openai/gpt-oss-20b","llama-3.1-8b-instant"]
    )
    st.caption("Powered by Groq LLMs")

# ---------- DOC CREATOR ----------
def create_doc(text):
    doc = Document()

    doc.add_heading("Improved Contract",0)

    p = doc.add_paragraph()
    run = p.add_run("Generated by Dracu-Law AI\n")
    run.italic = True

    doc.add_paragraph("")

    for line in text.split("\n"):
        doc.add_paragraph(line)

    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer


# ---------- TABS ----------
tab1, tab2, tab3 = st.tabs([
    "Analyze Contract",
    "Compare Contracts",
    "Improve Contract"
])

# =========================================================
# TAB 1 — ANALYZE
# =========================================================
with tab1:

    file = st.file_uploader("Upload contract PDF", type=["pdf"], key="single")

    if file:
        st.success("File uploaded")

        if st.button("Analyze"):

            text = extract_text(file)
            raw = analyze_contract(text, model_choice)
            result = format_results(raw)

            st.subheader("Risk Level")

            label,color = get_risk_label(result["risk_score"])

            col1,col2,col3 = st.columns([1,2,1])
            with col2:
                st.metric("Score", result["risk_score"])
                st.progress(result["risk_score"]/10)
                st.write(label)

            st.divider()

            c1,c2 = st.columns(2)

            with c1:
                st.subheader("Red Flags")
                for f in result["red_flags"]:
                    st.warning(f)

            with c2:
                st.subheader("Suggestions")
                for s in result["suggestions"]:
                    st.info(s)

            st.subheader("Summary")
            st.write(result["explanation"])

            st.session_state.last_contract = text
            st.session_state.last_flags = result["red_flags"]

# =========================================================
# TAB 2 — COMPARE
# =========================================================
with tab2:

    f1 = st.file_uploader("Upload Contract A", type=["pdf"], key="a")
    f2 = st.file_uploader("Upload Contract B", type=["pdf"], key="b")

    if f1 and f2:

        if st.button("Compare Now"):

            t1 = extract_text(f1)
            t2 = extract_text(f2)

            verdict = compare_contracts(t1,t2,model_choice)

            st.success("AI Verdict")
            st.write(verdict)

# =========================================================
# TAB 3 — IMPROVE CONTRACT
# =========================================================
with tab3:

    if "last_contract" not in st.session_state:
        st.info("Analyze a contract first.")
    else:

        st.write("Select clauses you want removed or improved")

        chosen=[]
        for flag in st.session_state.last_flags:
            if st.checkbox(flag):
                chosen.append(flag)

        if st.button("Generate Improved Version"):

            if not chosen:
                st.warning("Select at least one clause")
            else:

                improved = rewrite_contract(
                    st.session_state.last_contract,
                    chosen,
                    model_choice
                )

                st.subheader("Improved Contract")
                st.text_area("",improved,height=400)

                doc_file = create_doc(improved)

                st.download_button(
                    "Download as Word Document",
                    doc_file,
                    file_name="Improved_Contract.docx",
                    mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                )