import streamlit as st
from dotenv import load_dotenv
load_dotenv()

from parser import extract_text
from analyzer import analyze_contract, compare_contracts, rewrite_contract
from formatter import format_results, get_risk_label

import hashlib
import base64
from io import BytesIO
from docx import Document

st.set_page_config(page_title="Dracu-Law", page_icon="⚖", layout="wide")

# ---------- LOGO ----------
def get_base64_image(path):
    try:
        with open(path, "rb") as file_obj:
            return base64.b64encode(file_obj.read()).decode()
    except Exception as e:
        st.warning(f"Logo could not be loaded: {e}")
        return None

logo = get_base64_image("logo.png")

# ---------- NAVBAR ----------
st.markdown(f"""
<div style="
display:flex;
align-items:center;
gap:15px;
padding:14px 30px;
background:linear-gradient(90deg,#1c1c1e,#111);
border-bottom:3px solid #c0392b;
border-radius:0 0 12px 12px;
">
{f'<img src="data:image/png;base64,{logo}" style="height:65px">' if logo else "⚖"}
<div>
<div style="font-size:28px;font-weight:800;color:white;">Dracu<span style="color:#e74c3c">-Law</span></div>
<div style="color:#aaa;font-size:12px;">AI Legal Intelligence Engine</div>
</div>
</div>
""", unsafe_allow_html=True)

st.markdown("<h1 style='text-align:center;margin-top:25px;'>AI Contract Intelligence Platform</h1>", unsafe_allow_html=True)
st.divider()

# ---------- SIDEBAR ----------
ALLOWED_MODELS = [
    "llama-3.3-70b-versatile",
    "openai/gpt-oss-120b",
    "openai/gpt-oss-20b",
    "llama-3.1-8b-instant"
]

with st.sidebar:
    st.header("⚙ Settings")
    model_choice = st.selectbox("Model", ALLOWED_MODELS)
    if model_choice not in ALLOWED_MODELS:
        st.error("Invalid model selected.")
        st.stop()
    st.caption("Powered by Groq LLMs")

    st.divider()

    # IMPROVEMENT 3: Clear & Start Over
    st.markdown("**🔄 Session**")
    if st.button("Clear & Start Over", key="btn_clear"):
        for k in list(st.session_state.keys()):
            del st.session_state[k]
        st.success("Session cleared!")
        st.rerun()

# ---------- HELPERS ----------
def get_file_hash(uploaded_file):
    uploaded_file.seek(0)
    content = uploaded_file.read()
    uploaded_file.seek(0)
    return hashlib.md5(content).hexdigest()

def create_doc(text):
    doc = Document()
    doc.add_heading("Improved Contract", 0)
    p = doc.add_paragraph()
    run = p.add_run("Generated by Dracu-Law AI\n")
    run.italic = True
    doc.add_paragraph("")
    for line in text.split("\n"):
        stripped = line.strip()
        if not stripped:
            doc.add_paragraph("")
        elif stripped.isupper() and len(stripped) > 3:
            doc.add_heading(stripped, level=2)
        elif stripped.endswith(":") and len(stripped) < 60:
            doc.add_heading(stripped.rstrip(":"), level=3)
        else:
            doc.add_paragraph(line)
    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer

# IMPROVEMENT 2: Color-coded risk display
def render_risk_display(score):
    if score is None:
        st.warning("Risk score unavailable.")
        return
    if score <= 3:
        color   = "#27ae60"
        bg      = "#eafaf1"
        icon    = "✅"
        verdict = "Low Risk — generally safe to sign"
    elif score <= 6:
        color   = "#f39c12"
        bg      = "#fef9e7"
        icon    = "⚠️"
        verdict = "Moderate Risk — review flagged clauses carefully"
    else:
        color   = "#e74c3c"
        bg      = "#fdedec"
        icon    = "🚨"
        verdict = "High Risk — seek legal advice before signing"

    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        st.markdown(
            f"<div style='background:{bg};border:2px solid {color};border-radius:14px;"
            f"padding:24px 28px;text-align:center;margin-bottom:12px;'>"
            f"<div style='font-size:40px;margin-bottom:6px;'>{icon}</div>"
            f"<div style='font-size:52px;font-weight:900;color:{color};line-height:1;'>{score}"
            f"<span style='font-size:22px;color:#888;'>/10</span></div>"
            f"<div style='font-size:15px;color:{color};font-weight:600;margin-top:8px;'>{verdict}</div>"
            f"</div>",
            unsafe_allow_html=True
        )
        st.progress(min(max(score / 10, 0.0), 1.0))

# ---------- TABS ----------
tab1, tab2, tab3 = st.tabs([
    "Analyze Contract",
    "Compare Contracts",
    "Improve Contract"
])

# =========================================================
# TAB 1 — ANALYZE
# =========================================================
with tab1:

    uploaded_file = st.file_uploader("Upload contract PDF", type=["pdf"], key="single")

    if uploaded_file:
        st.success("File uploaded")
        file_hash = get_file_hash(uploaded_file)

        if st.button("Analyze", key="btn_analyze"):
            for key in ["last_contract", "last_flags", "last_hash", "last_result"]:
                st.session_state.pop(key, None)

            try:
                with st.spinner("Extracting text from PDF..."):
                    text = extract_text(uploaded_file)

                with st.spinner("Analyzing contract with AI (this may take 10–30 seconds)..."):
                    raw = analyze_contract(text, model_choice)

                result = format_results(raw)

                st.session_state.last_contract = text
                st.session_state.last_flags    = result["red_flags"]
                st.session_state.last_hash     = file_hash
                st.session_state.last_result   = result

            except Exception as e:
                st.error(f"Analysis failed: {e}")
                st.stop()

        if st.session_state.get("last_hash") == file_hash and "last_result" in st.session_state:
            result = st.session_state.last_result

            # IMPROVEMENT 2: Color-coded risk card
            st.subheader("Risk Level")
            render_risk_display(result.get("risk_score"))
            st.divider()

            c1, c2 = st.columns(2)
            with c1:
                st.subheader("Red Flags")
                for flag in result["red_flags"]:
                    st.warning(flag)
            with c2:
                st.subheader("Suggestions")
                for suggestion in result["suggestions"]:
                    st.info(suggestion)

            st.subheader("Summary")
            st.write(result["explanation"])

# =========================================================
# TAB 2 — COMPARE
# =========================================================
with tab2:

    f1 = st.file_uploader("Upload Contract A", type=["pdf"], key="a")
    f2 = st.file_uploader("Upload Contract B", type=["pdf"], key="b")

    # IMPROVEMENT 5: Empty state hints
    if f1 and not f2:
        st.warning("📂 Please upload **Contract B** to continue.")
    elif f2 and not f1:
        st.warning("📂 Please upload **Contract A** to continue.")

    if f1 and f2:

        if st.button("Compare Now", key="btn_compare"):
            try:
                with st.spinner("Extracting text from both contracts..."):
                    t1 = extract_text(f1)
                    t2 = extract_text(f2)

                with st.spinner("Comparing contracts with AI..."):
                    verdict = compare_contracts(t1, t2, model_choice)

                st.session_state.compare_verdict = verdict

            except Exception as e:
                st.error(f"Comparison failed: {e}")

        if "compare_verdict" in st.session_state:
            verdict = st.session_state.compare_verdict

            lines = verdict.strip().split("\n")
            winner_line     = ""
            reason_line     = ""
            differences     = []
            current_section = None

            for line in lines:
                line = line.strip()
                if not line:
                    continue
                if line.upper().startswith("WINNER"):
                    winner_line = line.split(":", 1)[-1].strip()
                    current_section = "winner"
                elif line.upper().startswith("REASON"):
                    reason_line = line.split(":", 1)[-1].strip()
                    current_section = "reason"
                elif "KEY DIFF" in line.upper():
                    current_section = "diff"
                elif current_section == "reason" and not reason_line:
                    reason_line = line
                elif current_section == "diff" and line.startswith(("-", "\u2022", "*")):
                    differences.append(line.lstrip("-\u2022* ").strip())
                elif current_section == "diff" and line:
                    differences.append(line.strip())

            st.divider()
            st.markdown("### \u2696\ufe0f Contract Comparison Verdict")
            st.caption("AI ANALYSIS")
            st.divider()

            winner_text = winner_line or "See full analysis below"
            st.markdown("**\U0001f3c6 WINNER**")
            st.success(f"### {winner_text}")

            if reason_line:
                st.markdown("")
                st.markdown("**\U0001f4cb REASON**")
                st.info(reason_line)

            if differences:
                st.markdown("")
                st.markdown("**\U0001f50d KEY DIFFERENCES**")
                st.markdown("")
                for i, item in enumerate(differences, 1):
                    col_num, col_text = st.columns([0.06, 0.94])
                    with col_num:
                        st.markdown(
                            f"<div style='background:#e74c3c;color:white;border-radius:50%;"
                            f"width:28px;height:28px;display:flex;align-items:center;"
                            f"justify-content:center;font-size:12px;font-weight:700;"
                            f"margin-top:4px;'>{i}</div>",
                            unsafe_allow_html=True
                        )
                    with col_text:
                        st.markdown(item)
                    st.markdown("---")

# =========================================================
# TAB 3 — IMPROVE CONTRACT
# =========================================================
with tab3:

    if "last_contract" not in st.session_state or "last_flags" not in st.session_state:
        st.info("Please analyze a contract in the **Analyze Contract** tab first.")
    else:
        st.write("Select clauses you want removed or improved:")

        chosen = []
        for flag in st.session_state.last_flags:
            flag_key = f"flag_{hashlib.md5(flag.encode()).hexdigest()}"
            if st.checkbox(flag, key=flag_key):
                chosen.append(flag)

        if st.button("Generate Improved Version", key="btn_improve"):
            if not chosen:
                st.warning("Please select at least one clause to improve.")
            else:
                try:
                    with st.spinner("Generating improved contract..."):
                        improved = rewrite_contract(
                            st.session_state.last_contract,
                            chosen,
                            model_choice
                        )
                    st.session_state.improved_contract = improved

                except Exception as e:
                    st.error(f"Failed to generate improved contract: {e}")

        # IMPROVEMENT 1: Success banner + persistent result display
        if "improved_contract" in st.session_state:
            st.success("✅ Contract improved successfully!")
            st.subheader("Improved Contract")
            st.text_area("", st.session_state.improved_contract, height=400)

            doc_file = create_doc(st.session_state.improved_contract)
            st.download_button(
                "⬇️ Download as Word Document",
                doc_file,
                file_name="Improved_Contract.docx",
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                key="btn_download"
            )

# =========================================================
# FOOTER — IMPROVEMENT 7
# =========================================================
st.divider()
st.markdown(
    "<div style='text-align:center;color:#666;font-size:13px;padding:12px 0 20px;'>"
    "⚖️ <strong>Dracu-Law</strong> · Powered by <strong>Groq LLMs</strong> · Built with <strong>Streamlit</strong>"
    "<br><span style='font-size:11px;'>AI-generated analysis is not a substitute for professional legal advice.</span>"
    "</div>",
    unsafe_allow_html=True
)